### ISSUE TITLE
Not possible to interpolate variables on keyspace replication

### ISSUE THREAD

**Issue by nachogiljaldo** [hawkular/cassalog#8]
Hi everyone,

I'm trying to run the following script:
```
createKeyspace {
  version 1
  name keyspace
  author 'admin'
  description 'create keyspace test'
  replication {
    replication_factor replicationFactor
  }
}
```
```
def cassalog = new CassalogImpl(session: session)
    def replicationFactor = 3
    cassalog.execute(script, [keyspace: keyspace, replicationFactor: replicationFactor])
```

but it does not work. It runs smoothly but replaces my provided replicationFactor with the default value 1. Same happens with the replicationStrategy.

**Comment by nachogiljaldo** [comment]
I just added a PR that should fix it. Please let me know when could you merge it and release a version fixing it.
If you can't for whatever reason release 0.5.0 please could you port it to 0.4.3 ?

Thanks in advance!

**Comment by jsanda** [comment]
Thanks for the PR. I haven't had a chance to review yet, but I will get to it before next week. There is another PR recently merged, so after this PR I will gladly do another release.

**Comment by nachogiljaldo** [comment]
That would be awesome! thanks @jsanda
